import { cn } from '@/lib/cn';

/**
 * The site's logo mark and loading spinner, a six-spoke forged wheel in the
 * Volk TE37 idiom: straight spokes that flare slightly toward a deep outer
 * lip, and a five-lug hub.
 *
 * Drawn as flat shapes rather than an outline so it stays legible at 24px in
 * the nav, where an outlined wheel turns into a grey smudge. Spokes are
 * generated by rotating one path, so the count is a single number to change.
 */
export function Wheel({
  className,
  spokes = 6,
  spinning = false,
}: {
  className?: string;
  spokes?: number;
  spinning?: boolean;
}) {
  const C = 50;

  /**
   * One spoke, pointing up, before rotation.
   *
   * Narrow at the hub (±5.5) and wider at the rim (±7.6), with the long sides
   * bowed very slightly inward, that concave taper is what makes it read as a
   * forged wheel rather than a pie slice.
   */
  const spoke = (
    <path
      d="M 44.5 35
         Q 43.4 23 42.4 13
         L 57.6 13
         Q 56.6 23 55.5 35
         Z"
      fill="currentColor"
    />
  );

  const lugs = Array.from({ length: 5 }, (_, i) => {
    // Rotated -90° so one lug sits at the top, matching the reference.
    const a = ((i / 5) * 360 - 90) * (Math.PI / 180);
    return (
      <circle
        key={i}
        cx={C + Math.cos(a) * 10.5}
        cy={C + Math.sin(a) * 10.5}
        r={2.3}
        className="fill-paper"
      />
    );
  });

  return (
    <svg
      viewBox="0 0 100 100"
      aria-hidden
      className={cn(spinning && 'animate-[spin_2.2s_linear_infinite]', className)}
      fill="none"
    >
      {/* Outer lip, the thick barrel edge the TE37 is known for */}
      <circle cx={C} cy={C} r={45.5} stroke="currentColor" strokeWidth={5} />
      {/* Inner rim face */}
      <circle cx={C} cy={C} r={40} stroke="currentColor" strokeWidth={2} />

      {Array.from({ length: spokes }, (_, i) => (
        <g key={i} transform={`rotate(${(i * 360) / spokes} ${C} ${C})`}>
          {spoke}
        </g>
      ))}

      {/* Hub face with lug holes and centre bore */}
      <circle cx={C} cy={C} r={17} fill="currentColor" />
      {lugs}
      <circle cx={C} cy={C} r={5.5} className="fill-paper" />
    </svg>
  );
}
